name = "cf-ssr-template-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2021-09-24"
zone_id = ""
route = ""

kv_namespaces = [
  { binding = "POSTS", id = "" },
  { binding = "USERS", id = "" },
  { binding = "USERNAMES", id = ""},
  { binding = "TOKENS", id = ""},
  { binding = "POSTS_LATEST", id = ""}
]

[site]
bucket = "./public"
entry-point = '.'

[build]
command = "npm run build:prod"

[build.upload]
format = "service-worker"

[miniflare]
kv_persist = true