GET http://localhost:5000/api/posts
content-type: application/json
cookie: testing=test;

###

GET http://localhost:5000/api/posts/9-EjAfdVU2
content-type: application/json

###

POST http://localhost:5000/api/posts
content-type: application/json

{
    "title": "Testing post",
    "content": "I am an awesome post"
}

###

DELETE http://localhost:5000/api/posts/9-EjAfdVU2
content-type: application/json